#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

:?:ll `t::I'll 
:?:qz `t::I've 
:?:jc `t::able 
:?:ab `t::about 
:?:bv `t::above 
:?:ac `t::account 
:?:nj `t::across 
:?:dd `t::added 
:?:zw `t::affection 
:?:iw `t::afraid 
:?:af `t::after 
:?:ew `t::afterwards 
:?:ag `t::again 
:?:aa `t::against 
:?:l `t::all 
:?:ao `t::almost 
:?:ln `t::alone 
:?:fj `t::along 
:?:dq `t::already 
:?:gx `t::also 
:?:zj `t::altogether 
:?:al `t::always 
:?:bb `t::among 
:?:n `t::and 
:?:gy `t::angry 
:?:ar `t::another 
:?:nw `t::answer 
:?:nd `t::answered 
:?:ay `t::anything 
:?:pc `t::appearance 
:?:ap `t::appeared 
:?:jd `t::arms 
:?:ad `t::asked 
:?:ux `t::attention 
:?:mx `t::aunt 
:?:aw `t::away 
:?:ba `t::back 
:?:gk `t::bear 
:?:uf `t::beautiful 
:?:yj `t::beauty 
:?:bm `t::became 
:?:bc `t::because 
:?:qp `t::become 
:?:bn `t::been 
:?:bf `t::before 
:?:ea `t::began 
:?:vz `t::beginning 
:?:bd `t::behind 
:?:bg `t::being 
:?:bl `t::believe 
:?:zp `t::believed 
:?:lz `t::besides 
:?:bs `t::best 
:?:br `t::better 
:?:bt `t::between 
:?:yd `t::beyond 
:?:bk `t::black 
:?:sq `t::blood 
:?:ku `t::body 
:?:qx `t::book 
:?:bo `t::both 
:?:ix `t::bring 
:?:xg `t::broken 
:?:bh `t::brother 
:?:bu `t::brought 
:?:bi `t::business 
:?:u `t::but 
:?:cl `t::call 
:?:cd `t::called 
:?:ca `t::came 
:?:gb `t::can't 
:?:ct `t::cannot 
:?:xs `t::captain 
:?:cj `t::care 
:?:zo `t::carriage 
:?:np `t::carried 
:?:zr `t::carry 
:?:hj `t::case 
:?:yz `t::caught 
:?:vm `t::cause 
:?:cn `t::certain 
:?:ty `t::certainly 
:?:nx `t::chair 
:?:vu `t::chance 
:?:kj `t::change 
:?:cp `t::chapter 
:?:cc `t::character 
:?:ch `t::child 
:?:ci `t::children 
:?:hc `t::church 
:?:uc `t::circumstances 
:?:vj `t::clear 
:?:cs `t::close 
:?:jv `t::cold 
:?:ce `t::come 
:?:uw `t::comes 
:?:cf `t::comfort 
:?:cg `t::coming 
:?:qb `t::common 
:?:cm `t::company 
:?:zd `t::consider 
:?:zf `t::considered 
:?:nn `t::continued 
:?:cv `t::conversation 
:?:tx `t::corner 
:?:co `t::could 
:?:cy `t::country 
:?:cu `t::course 
:?:eu `t::creature 
:?:cr `t::cried 
:?:dk `t::dark 
:?:au `t::daughter 
:?:da `t::days 
:?:jb `t::dead 
:?:dl `t::deal 
:?:de `t::dear 
:?:dh `t::death 
:?:dp `t::deep 
:?:yp `t::desire 
:?:vv `t::didn't 
:?:di `t::different 
:?:lb `t::dinner 
:?:tc `t::distance 
:?:dc `t::doctor 
:?:ds `t::does 
:?:dg `t::doing 
:?:dt `t::don't 
:?:oe `t::done 
:?:dr `t::door 
:?:du `t::doubt 
:?:dn `t::down 
:?:zx `t::dress 
:?:dw `t::drew 
:?:ui `t::during 
:?:wp `t::duty 
:?:ec `t::each 
:?:mj `t::early 
:?:zy `t::earth 
:?:zb `t::easily 
:?:vf `t::easy 
:?:ff `t::effect 
:?:dx `t::either 
:?:el `t::else 
:?:eh `t::enough 
:?:jl `t::entered 
:?:xb `t::entirely 
:?:en `t::even 
:?:ei `t::evening 
:?:ev `t::ever 
:?:ey `t::every 
:?:eb `t::everybody 
:?:vg `t::everything 
:?:xy `t::exactly 
:?:ex `t::except 
:?:xc `t::exclaimed 
:?:xt `t::expect 
:?:xd `t::expected 
:?:es `t::eyes 
:?:fa `t::face 
:?:fc `t::fact 
:?:jx `t::fair 
:?:xe `t::fall 
:?:fy `t::family 
:?:xm `t::fancy 
:?:fr `t::father 
:?:yb `t::father's 
:?:gp `t::fear 
:?:fl `t::feel 
:?:fg `t::feeling 
:?:tq `t::feelings 
:?:kq `t::feet 
:?:gj `t::fell 
:?:fw `t::fellow 
:?:fe `t::felt 
:?:wx `t::figure 
:?:fn `t::find 
:?:gz `t::fine 
:?:ir `t::fire 
:?:fi `t::first 
:?:fv `t::five 
:?:lw `t::followed 
:?:uk `t::foot 
:?:f `t::for 
:?:fm `t::form 
:?:sj `t::former 
:?:zi `t::forth 
:?:sz `t::fortune 
:?:rw `t::forward 
:?:fo `t::found 
:?:jh `t::four 
:?:zm `t::free 
:?:fd `t::friend 
:?:fs `t::friends 
:?:r `t::from 
:?:yt `t::front 
:?:fu `t::full 
:?:fh `t::further 
:?:ga `t::gave 
:?:nl `t::general 
:?:gn `t::gentleman 
:?:gm `t::gentlemen 
:?:lq `t::getting 
:?:gl `t::girl 
:?:gi `t::give 
:?:gv `t::given 
:?:vn `t::giving 
:?:fp `t::glad 
:?:zc `t::glass 
:?:gg `t::going 
:?:ge `t::gone 
:?:gd `t::good 
:?:zn `t::grave 
:?:gr `t::great 
:?:ze `t::green 
:?:gw `t::grew 
:?:gu `t::ground 
:?:d `t::had 
:?:jj `t::hair 
:?:az `t::half 
:?:ha `t::hand 
:?:ns `t::hands 
:?:nm `t::handsome 
:?:lj `t::happened 
:?:xj `t::happiness 
:?:hy `t::happy 
:?:eq `t::hard 
:?:rl `t::hardly 
:?:v `t::have 
:?:hg `t::having 
:?:wq `t::he's 
:?:hd `t::head 
:?:er `t::hear 
:?:ed `t::heard 
:?:ht `t::heart 
:?:yc `t::heaven 
:?:hv `t::heavy 
:?:hq `t::held 
:?:ep `t::help 
:?:e `t::her 
:?:hr `t::here 
:?:ef `t::herself 
:?:gh `t::high 
:?:m `t::him 
:?:hf `t::himself 
:?:i `t::his 
:?:iq `t::hold 
:?:om `t::home 
:?:iz `t::honour 
:?:hp `t::hope 
:?:js `t::horse 
:?:wb `t::horses 
:?:hu `t::hour 
:?:jr `t::hours 
:?:ho `t::house 
:?:hw `t::however 
:?:xl `t::human 
:?:mz `t::hundred 
:?:hb `t::husband 
:?:ia `t::idea 
:?:iy `t::immediately 
:?:ip `t::impossible 
:?:id `t::indeed 
:?:pq `t::instead 
:?:ka `t::interest 
:?:io `t::into 
:?:cz `t::it's 
:?:sf `t::itself 
:?:ju `t::just 
:?:ke `t::keep 
:?:kt `t::kept 
:?:ki `t::kind 
:?:kw `t::knew 
:?:kn `t::know 
:?:rz `t::knowing 
:?:kl `t::knowledge 
:?:ko `t::known 
:?:ks `t::knows 
:?:qv `t::ladies 
:?:ly `t::lady 
:?:kk `t::laid 
:?:lr `t::large 
:?:la `t::last 
:?:jf `t::late 
:?:yv `t::laugh 
:?:lu `t::laughed 
:?:ls `t::least 
:?:av `t::leave 
:?:wz `t::leaving 
:?:lt `t::left 
:?:qj `t::length 
:?:bj `t::less 
:?:et `t::letter 
:?:lf `t::life 
:?:lh `t::light 
:?:le `t::like 
:?:ik `t::likely 
:?:lp `t::lips 
:?:li `t::little 
:?:iv `t::live 
:?:vd `t::lived 
:?:vi `t::living 
:?:lo `t::long 
:?:jp `t::longer 
:?:lk `t::look 
:?:ld `t::looked 
:?:lg `t::looking 
:?:zt `t::looks 
:?:jy `t::lord 
:?:hz `t::lost 
:?:lv `t::love 
:?:qq `t::loved 
:?:ma `t::made 
:?:mk `t::make 
:?:ai `t::making 
:?:ae `t::manner 
:?:mn `t::many 
:?:qw `t::marriage 
:?:jn `t::married 
:?:qh `t::marry 
:?:bp `t::master 
:?:bx `t::matter 
:?:bq `t::mean 
:?:dz `t::means 
:?:qc `t::meant 
:?:pj `t::meet 
:?:zs `t::mentioned 
:?:mi `t::might 
:?:yx `t::miles 
:?:md `t::mind 
:?:gf `t::mine 
:?:xk `t::minute 
:?:iu `t::minutes 
:?:ss `t::miss 
:?:mm `t::moment 
:?:ny `t::money 
:?:xf `t::months 
:?:mo `t::more 
:?:mg `t::morning 
:?:ms `t::most 
:?:mh `t::mother 
:?:qf `t::mouth 
:?:mv `t::moved 
:?:mu `t::much 
:?:mt `t::must 
:?:mf `t::myself 
:?:na `t::name 
:?:ua `t::natural 
:?:nu `t::nature 
:?:nr `t::near 
:?:xr `t::nearly 
:?:nc `t::necessary 
:?:ky `t::need 
:?:nh `t::neither 
:?:ne `t::never 
:?:yq `t::news 
:?:nt `t::next 
:?:ni `t::night 
:?:nb `t::nobody 
:?:ji `t::none 
:?:o `t::not 
:?:ng `t::nothing 
:?:wj `t::notice 
:?:oj `t::object 
:?:rj `t::obliged 
:?:ob `t::observed 
:?:qg `t::occasion 
:?:ft `t::often 
:?:oc `t::once 
:?:oy `t::only 
:?:op `t::open 
:?:kh `t::opened 
:?:jg `t::opinion 
:?:kx `t::order 
:?:ot `t::other 
:?:cx `t::others 
:?:ou `t::ought 
:?:ov `t::over 
:?:pa `t::part 
:?:rq `t::particular 
:?:vy `t::party 
:?:rx `t::pass 
:?:pd `t::passed 
:?:kv `t::past 
:?:pp `t::people 
:?:pf `t::perfectly 
:?:pe `t::perhaps 
:?:pn `t::person 
:?:xu `t::piece 
:?:pl `t::place 
:?:vb `t::play 
:?:vx `t::pleasant 
:?:jw `t::please 
:?:kz `t::pleased 
:?:ps `t::pleasure 
:?:pt `t::point 
:?:po `t::poor 
:?:pi `t::possible 
:?:xq `t::pounds 
:?:pw `t::power 
:?:tj `t::presence 
:?:pr `t::present 
:?:uv `t::presently 
:?:py `t::pretty 
:?:pb `t::probably 
:?:pm `t::promise 
:?:pu `t::purpose 
:?:zq `t::putting 
:?:qn `t::question 
:?:qt `t::quiet 
:?:qu `t::quite 
:?:ra `t::rather 
:?:xx `t::reached 
:?:dj `t::read 
:?:dy `t::ready 
:?:vh `t::real 
:?:ry `t::really 
:?:rn `t::reason 
:?:rc `t::received 
:?:za `t::regard 
:?:qo `t::remained 
:?:rm `t::remember 
:?:xz `t::repeated 
:?:rp `t::replied 
:?:rv `t::resolved 
:?:rs `t::rest 
:?:rr `t::return 
:?:rt `t::returned 
:?:ri `t::right 
:?:oa `t::road 
:?:ro `t::room 
:?:mq `t::rose 
:?:rd `t::round 
:?:c `t::said 
:?:sx `t::sake 
:?:sa `t::same 
:?:yi `t::saying 
:?:sy `t::says 
:?:zu `t::scarcely 
:?:xv `t::school 
:?:eo `t::second 
:?:xh `t::secret 
:?:ja `t::seeing 
:?:qs `t::seem 
:?:sd `t::seemed 
:?:em `t::seems 
:?:aj `t::seen 
:?:vp `t::send 
:?:fq `t::sense 
:?:jm `t::sent 
:?:vc `t::service 
:?:sv `t::several 
:?:sl `t::shall 
:?:s `t::she 
:?:yk `t::shook 
:?:cw `t::short 
:?:sh `t::should 
:?:sw `t::show 
:?:xp `t::showed 
:?:si `t::side 
:?:gt `t::sight 
:?:ic `t::silence 
:?:qa `t::silent 
:?:sc `t::since 
:?:jk `t::sister 
:?:lm `t::sitting 
:?:xa `t::sleep 
:?:sm `t::small 
:?:ml `t::smile 
:?:zv `t::society 
:?:se `t::some 
:?:sg `t::something 
:?:oi `t::sometimes 
:?:sn `t::soon 
:?:ox `t::sorry 
:?:cb `t::sort 
:?:mc `t::soul 
:?:pz `t::sound 
:?:sp `t::speak 
:?:pg `t::speaking 
:?:uj `t::spirit 
:?:vq `t::spirits 
:?:sk `t::spoke 
:?:oz `t::stand 
:?:oq `t::standing 
:?:gq `t::state 
:?:jz `t::stay 
:?:st `t::still 
:?:od `t::stood 
:?:zh `t::stop 
:?:tp `t::stopped 
:?:ql `t::story 
:?:km `t::strange 
:?:qm `t::street 
:?:xo `t::strength 
:?:rg `t::strong 
:?:rk `t::struck 
:?:sb `t::subject 
:?:su `t::such 
:?:zl `t::sudden 
:?:uy `t::suddenly 
:?:ue `t::suppose 
:?:uo `t::supposed 
:?:sr `t::sure 
:?:zk `t::surprise 
:?:tb `t::`tle 
:?:ta `t::take 
:?:ak `t::taken 
:?:kg `t::taking 
:?:ej `t::talk 
:?:tz `t::talking 
:?:kr `t::tears 
:?:tl `t::tell 
:?:tn `t::than 
:?:nk `t::thank 
:?:h `t::that 
:?:db `t::that's 
:?:t `t::the 
:?:tr `t::their 
:?:tm `t::them 
:?:tv `t::themselves 
:?:te `t::then 
:?:th `t::there 
:?:lx `t::there's 
:?:tf `t::therefore 
:?:ts `t::these 
:?:k `t::they 
:?:hn `t::thing 
:?:ig `t::things 
:?:tk `t::think 
:?:hk `t::thinking 
:?:j `t::this 
:?:hs `t::those 
:?:tu `t::though 
:?:tt `t::thought 
:?:gs `t::thoughts 
:?:xi `t::thousand 
:?:ee `t::three 
:?:tg `t::through 
:?:fb `t::thus 
:?:il `t::till 
:?:ti `t::time 
:?:im `t::times 
:?:og `t::together 
:?:td `t::told 
:?:nz `t::tone 
:?:oo `t::took 
:?:tw `t::towards 
:?:ow `t::town 
:?:qd `t::tried 
:?:rb `t::trouble 
:?:ru `t::true 
:?:rh `t::truth 
:?:ez `t::turn 
:?:ud `t::turned 
:?:ug `t::turning 
:?:wy `t::twenty 
:?:yw `t::uncle 
:?:ur `t::under 
:?:ut `t::understand 
:?:zg `t::unless 
:?:qe `t::until 
:?:un `t::upon 
:?:bz `t::used 
:?:ul `t::usual 
:?:ve `t::very 
:?:vw `t::view 
:?:vt `t::visit 
:?:vo `t::voice 
:?:uz `t::wait 
:?:ym `t::waiting 
:?:hx `t::walk 
:?:kd `t::walked 
:?:ya `t::walking 
:?:wa `t::want 
:?:gc `t::wanted 
:?:w `t::was 
:?:ij `t::water 
:?:ek `t::week 
:?:wl `t::well 
:?:wn `t::went 
:?:p `t::were 
:?:z `t::what 
:?:wv `t::whatever 
:?:x `t::when 
:?:wh `t::where 
:?:hh `t::whether 
:?:g `t::which 
:?:hl `t::while 
:?:fz `t::white 
:?:ol `t::whole 
:?:wm `t::whom 
:?:os `t::whose 
:?:wf `t::wife 
:?:wi `t::will 
:?:uq `t::wind 
:?:ww `t::window 
:?:ih `t::wish 
:?:px `t::wished 
:?:b `t::with 
:?:ii `t::within 
:?:wt `t::without 
:?:wo `t::woman 
:?:jq `t::women 
:?:kb `t::won't 
:?:jt `t::wonder 
:?:wr `t::word 
:?:ws `t::words 
:?:wk `t::work 
:?:wd `t::world 
:?:nq `t::worse 
:?:vk `t::worth 
:?:q `t::would 
:?:xw `t::write 
:?:wg `t::wrong 
:?:yr `t::year 
:?:ye `t::years 
:?:y `t::you 
:?:yg `t::young 
:?:yo `t::your 
:?:yf `t::yourself 
